clavis:
  keycloak:
    url: http://localhost:8085
    realm: clavis-admin
    resource: admin-cli
    credentials:
      secret: EaWMwr4I5mtKVMaW3zoPOCMBSuRBJBJa
      username: clavis
      password: clavis

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8090
  servlet:
    context-path: /api

spring: # Spring Security Configuration
  banner:
    location: banner.txt
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${clavis.keycloak.url}/realms/${clavis.keycloak.realm}
          jwk-set-uri: ${clavis.keycloak.url}/realms/clavis-admin/protocol/openid-connect/certs
#  kafka:
#    bootstrap-servers: localhost:8087
#    consumer:
#      group-id: clavis



logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG





