server:
  port: 8090
  servlet:
    context-path: /api

spring:
  banner:
    location: banner.txt
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${clavis.security.keycloak.url}/realms/${clavis.security.keycloak.realm}
          jwk-set-uri: ${clavis.security.keycloak.url}/realms/clavis-admin/protocol/openid-connect/certs
  kafka:
    consumer:
      bootstrap-servers: ${clavis.kafka.bootstrap-servers}

clavis:
  security:
    api-config:
      whitelisted-urls:
        - /swagger-ui/*
        - /v3/api-docs/*
        - /public/*
        - /error/*
    keycloak:
      url: http://localhost:8085
      realm: clavis-admin
      resource: clavis-backend
      credentials:
        secret: clavis-backend
  kafka:
    bootstrap-servers: localhost:9092
    keycloak-topic: keycloak-event


logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG





