name: clavis-ci

on: [ push,pull_request ]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit tests
        run: mvn -B -q test
        working-directory: starter

      - name: Run tests
        run: mvn -B -q clean install
        working-directory: starter
