name: clavis-ci

on: [ push,pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit tests
        run: mvn test
        working-directory: starter/launcher

      - name: Run tests
        run: mvn clean install
        working-directory: starter/launcher
