# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}/.github/maven

      - name: Debug - List repo contents
        run: ls -R $GITHUB_WORKSPACE

      - name: Build with Maven
        run: mvn -B package --file starter/pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -f starter/pom.xml -s $GITHUB_WORKSPACE/.github/maven/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
